/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.exercicios_gui;

import javax.swing.JOptionPane;

/**
 *
 * @author Admin
 */
public class kg_em_planetas extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(kg_em_planetas.class.getName());

    /**
     * Creates new form kg_em_planetas
     */
    public kg_em_planetas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup2 = new javax.swing.ButtonGroup();
        campo1 = new javax.swing.JTextField();
        botao1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Mercurio = new javax.swing.JRadioButton();
        Marte = new javax.swing.JRadioButton();
        Saturno = new javax.swing.JRadioButton();
        Venus = new javax.swing.JRadioButton();
        Jupiter = new javax.swing.JRadioButton();
        Urano = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        botao1.setText("Calcular peso");
        botao1.addActionListener(this::botao1ActionPerformed);

        jLabel1.setText("Qual seu peso na terra (em kg)");

        jLabel2.setText("Selecione o planeta");

        buttonGroup2.add(Mercurio);
        Mercurio.setText("Mercurio");
        Mercurio.addActionListener(this::MercurioActionPerformed);

        buttonGroup2.add(Marte);
        Marte.setText("Marte");
        Marte.addActionListener(this::MarteActionPerformed);

        buttonGroup2.add(Saturno);
        Saturno.setText("Saturno");
        Saturno.addActionListener(this::SaturnoActionPerformed);

        buttonGroup2.add(Venus);
        Venus.setText("Venus");
        Venus.addActionListener(this::VenusActionPerformed);

        buttonGroup2.add(Jupiter);
        Jupiter.setText("Jupiter");
        Jupiter.addActionListener(this::JupiterActionPerformed);

        buttonGroup2.add(Urano);
        Urano.setText("urano");
        Urano.addActionListener(this::UranoActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Venus)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Mercurio)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Jupiter)
                                .addGap(18, 18, 18)
                                .addComponent(Urano))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Marte)
                                .addGap(18, 18, 18)
                                .addComponent(Saturno))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(campo1)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(7, 7, 7)
                        .addComponent(botao1)))
                .addContainerGap(134, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botao1))
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Mercurio)
                    .addComponent(Marte)
                    .addComponent(Saturno))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Venus)
                    .addComponent(Jupiter)
                    .addComponent(Urano))
                .addContainerGap(101, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MarteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MarteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MarteActionPerformed

    private void SaturnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaturnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SaturnoActionPerformed

    private void VenusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VenusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_VenusActionPerformed

    private void JupiterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JupiterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JupiterActionPerformed

    private void UranoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UranoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UranoActionPerformed

    private void botao1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao1ActionPerformed

        double numero1,mercurio,venus,marte,jupiter,saturno,urano;
        
        numero1 = Double.parseDouble(campo1.getText());
        

     
    if(Mercurio.isSelected()) {
          mercurio = ((numero1/10)*0.37);
          JOptionPane.showConfirmDialog(null,mercurio);
    } 
     
     if(Venus.isSelected()) {
         venus = ((numero1/10)*0.88);
         JOptionPane.showConfirmDialog(null,venus);
    } 
     
     if(Marte.isSelected()) {
         marte = ((numero1/10)*0.38);
          JOptionPane.showConfirmDialog(null,marte);
    } 
     
     if(Jupiter.isSelected()) {
         jupiter = ((numero1/10)*2.64);
          JOptionPane.showConfirmDialog(null,jupiter);
    } 
     
     if(Saturno.isSelected()) {
         saturno = ((numero1/10)*1.15);
          JOptionPane.showConfirmDialog(null,saturno);
    } 
    
 
     if(Urano.isSelected()) {
         urano = ((numero1/10)*1.17);
          JOptionPane.showConfirmDialog(null,urano);
    } 



    }//GEN-LAST:event_botao1ActionPerformed

    private void MercurioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MercurioActionPerformed



    }//GEN-LAST:event_MercurioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new kg_em_planetas().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton Jupiter;
    private javax.swing.JRadioButton Marte;
    private javax.swing.JRadioButton Mercurio;
    private javax.swing.JRadioButton Saturno;
    private javax.swing.JRadioButton Urano;
    private javax.swing.JRadioButton Venus;
    private javax.swing.JButton botao1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JTextField campo1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
